version: "3"

services:
  web:
    build:
      context: .
      dockerfile: build/web.Dockerfile
    environment:
      - "NODE_PATH=/app/node_modules/"
      - "ENVIRONMENT=${ENVIRONMENT}"
      - "FFMPEG_LOCATION=${FFMPEG_LOCATION}"
      - "PORT=${PORT}"
      - "PROCESSING_DIR=${PROCESSING_DIR}"
      - "REDDIT_CLIENT_ID=${REDDIT_CLIENT_ID}"
      - "REDDIT_CLIENT_SECRET=${REDDIT_CLIENT_SECRET}"
      - "REDDIT_USERNAME=${REDDIT_USERNAME}"
      - "REDDIT_PASSWORD=${REDDIT_PASSWORD}"
      - "REDDIT_USER_AGENT=${REDDIT_USER_AGENT}"
      - "REDDIT_SCAN_SUBS=${REDDIT_SCAN_SUBS}"
      - "LOGGER_ELASTICSEARCH_INDEX=${LOGGER_ELASTICSEARCH_INDEX}"
      - "LOGGER_ELASTICSEARCH_NODE=${LOGGER_ELASTICSEARCH_NODE}"
      - "LOGGER_LEVEL=${LOGGER_LEVEL}"
      - "STORAGE_S3_ENDPOINT=${STORAGE_S3_ENDPOINT}"
      - "STORAGE_S3_ACCESS_KEY_ID=${STORAGE_S3_ACCESS_KEY_ID}"
      - "STORAGE_S3_SECRET_ACCESS_KEY=${STORAGE_S3_SECRET_ACCESS_KEY}"
      - "STORAGE_S3_BUCKET=${STORAGE_S3_BUCKET}"
      - "TUCKBOT_API_URL=${TUCKBOT_API_URL}"
      - "TUCKBOT_API_TOKEN=${TUCKBOT_API_TOKEN}"
      - "TUCKBOT_FRONTEND_CDNURL=${TUCKBOT_FRONTEND_CDNURL}"
      - "TUCKBOT_FRONTEND_URL=${TUCKBOT_FRONTEND_URL}"
      - "ACM_ENDPOINT=${ACM_ENDPOINT}"
      - "ACM_API_TOKEN=${ACM_API_TOKEN}"
      - "ACM_BOT_TOKEN=${ACM_BOT_TOKEN}"
    ports:
      - 3002:3002
    restart: always
    volumes:
      - api-data:/data
volumes:
  api-data:
