version: "3"

services:
  web:
    build:
      context: .
      dockerfile: build/web.Dockerfile
    environment:
      - "NODE_PATH=/app/node_modules/"
      - "ENVIRONMENT=${ENVIRONMENT}"
      - "PORT=${PORT}"
      - "DATABASE_LOCATION=${DATABASE_LOCATION}"
      - "STORAGE_S3_ENDPOINT=${STORAGE_S3_ENDPOINT}"
      - "STORAGE_S3_ACCESS_KEY_ID=${STORAGE_S3_ACCESS_KEY_ID}"
      - "STORAGE_S3_SECRET_ACCESS_KEY=${STORAGE_S3_SECRET_ACCESS_KEY}"
      - "STORAGE_S3_BUCKET=${STORAGE_S3_BUCKET}"
      - "TUCKBOT_API_TOKEN=${TUCKBOT_API_TOKEN}"
      - "TUCKBOT_API_URL=${TUCKBOT_API_URL}"
    ports:
      - 3002:3002
    restart: always
    volumes:
      - api-data:/data
volumes:
  api-data:
