version: "3"

services:
  api:
    build:
      context: .
      dockerfile: build/api.Dockerfile
    environment:
      - "NODE_PATH=/app/node_modules/"
      - "ENVIRONMENT=${ENVIRONMENT}"
      - "PORT=${PORT}"
      - "DATABASE_LOCATION=${DATABASE_LOCATION}"
    ports:
      - 3002:3002
    restart: always
    volumes:
      - "/data"
